export const conversationData = [
  {
    id: "c1",
    link: "https://drive.google.com/drive/folders/1TLrTserv4wDvUW1Z8IcT6EqvGcPR9uIC?usp=drive_link",
    image: "/c1.webp",
    title: "Daily Conversation (1)",
    category: "conversations",
  },
  {
    id: "c2",
    link: "https://drive.google.com/drive/folders/11sFModT0361NGEP5OKy2lZziVJwa6yaz?usp=drive_link",
    image: "/c2.webp",
    title: "Daily Conversation (2)",
    category: "conversations",
  },
  {
    id: "c3",
    link: "https://drive.google.com/drive/folders/1_-5g_tiiQreRZAyfF-weXlS1SC75pShE?usp=drive_link",
    image: "/c3.webp",
    title: "Daily Conversation (3)",
    category: "conversations",
  },
  {
    id: "c4",
    link: "https://drive.google.com/drive/folders/1iDwrZbCZLX9pXHBO_wQ1q9aDimU9eyAm?usp=drive_link",
    image: "/c4.webp",
    title: "Daily Conversation (4)",
    category: "conversations",
  },
  {
    id: "c5",
    link: "https://drive.google.com/drive/folders/1XRlC9HczabvojVTahJGmPaiJureCBJbv?usp=drive_link",
    image: "/c5.webp",
    title: "Daily Conversation (5)",
    category: "conversations",
  },
  {
    id: "c6",
    link: "https://drive.google.com/drive/folders/1PMNmBavCB4SEvTLAa2qKh3m5Hzh31ciy?usp=drive_link",
    image: "/c6.webp",
    title: "Home Conversation (1)",
    category: "conversations",
  },
  {
    id: "c7",
    link: "https://drive.google.com/drive/folders/12kTIigRO2jiVDMD9u2mAzu01YdOKvV0o?usp=drive_link",
    image: "/c7.webp",
    title: "Home Conversation (2)",
    category: "conversations",
  },
  {
    id: "c8",
    link: "https://drive.google.com/drive/folders/1zYsS47OxLb0ZkEaw1oiBeIs1hW1kDG-f?usp=drive_link",
    image: "/c8.webp",
    title: "Home Conversation (3)",
    category: "conversations",
  },
  {
    id: "c9",
    link: "https://drive.google.com/drive/folders/10l5wHpSbjN66tO_vtSb5dFduWr0IWXpL?usp=drive_link",
    image: "/c9.webp",
    title: "Home Conversation (4)",
    category: "conversations",
  },
  {
    id: "c10",
    link: "https://drive.google.com/drive/folders/1nLdnFx37TcL2HjzLJYdHhmOH6L_eigRR?usp=drive_link",
    image: "/c10.webp",
    title: "Home Conversation (5)",
    category: "conversations",
  },
  {
    id: "c11",
    link: "https://drive.google.com/drive/folders/1iHfa8-vdNCnnaoOxfvcg0NypIdutQHAd?usp=drive_link",
    image: "/c11.webp",
    title: "Home Conversation (6)",
    category: "conversations",
  },
  {
    id: "c12",
    link: "https://drive.google.com/drive/folders/15EcQ39DmACt-RXJiZKXTMkqCZt7BW5KE?usp=drive_link",
    image: "/c12.webp",
    title: "Home Conversation (7)",
    category: "conversations",
  },
];

export const verbsData = [
  {
    id: "v1",
    link: "https://drive.google.com/drive/folders/18faH8VtR1xYKhQ3dkg2B7yQ59cxVbh-i?usp=drive_link",
    image: "/v1.webp",
    title: "Daily Verbs (1)",
    category: "verbs",
  },
  {
    id: "v2",
    link: "https://drive.google.com/drive/folders/18e9A5QIVLaOK8NErnDQPFrLVfbiPv_gg?usp=drive_link",
    image: "/v2.webp",
    title: "Daily Verbs (2)",
    category: "verbs",
  },
  {
    id: "v3",
    link: "https://drive.google.com/drive/folders/1z2KpduYkEP7AOPPeTjL6Vl9dhprv1Mjy?usp=drive_link",
    image: "/v3.webp",
    title: "Daily Verbs (3)",
    category: "verbs",
  },
  {
    id: "v4",
    link: "https://drive.google.com/drive/folders/1U5Qzukavgp5Hz2BqQoJDJRayYhu2jRcX?usp=drive_link",
    image: "/v4.webp",
    title: "Daily Verbs (4)",
    category: "verbs",
  },
  {
    id: "v5",
    link: "https://drive.google.com/drive/folders/1mnr6qngog0LBNTkU1xgPkj_1C3mmn2QY?usp=drive_link",
    image: "/v5.webp",
    title: "Daily Verbs (5)",
    category: "verbs",
  },
];

export const NounsData = [
  {
    id: "n1",
    link: "https://drive.google.com/drive/folders/1xCxO_vRNGJr60w1xuS1AsmH3HS0egNPM?usp=drive_link",
    image: "/n1.webp",
    title: "Daily Nouns (1)",
    category: "nouns",
  },
  {
    id: "n2",
    link: "https://drive.google.com/drive/folders/1mHhSn16jbz4jCgKf2l0VyTjw-Iu7jebd?usp=drive_link",
    image: "/n2.webp",
    title: "Daily Nouns (2)",
    category: "nouns",
  },
  {
    id: "n3",
    link: "https://drive.google.com/drive/folders/1xg3tkbKTWE9OlQ2akxXsiktaVzsSw83b?usp=drive_link",
    image: "/n3.webp",
    title: "Daily Nouns (3)",
    category: "nouns",
  },
  {
    id: "n4",
    link: "https://drive.google.com/drive/folders/1PiTDEcb-DcIBZYU8eosEd--4XrSKYYCB?usp=drive_link",
    image: "/n4.webp",
    title: "Daily Nouns (4)",
    category: "nouns",
  },
  {
    id: "n5",
    link: "https://drive.google.com/drive/folders/1dt1J7v3JjN_7C0Of2_inotxsjZo-xiL6?usp=drive_link",
    image: "/n5.webp",
    title: "Daily Nouns (5)",
    category: "nouns",
  },
];
